#!/bin/sh
#
# Build indexes for main page, categories, tags, etc.
#

if [ -f config ] ; then
  source config
fi

THEME=${THEME:-"basic"}
echo "Theme: $THEME"
BASE_DIR="v2"
BASE_URL="/$BASE_DIR"
DB=".db/index.csv"
DS='/[0-9][0-9][0-9][0-9]'
LIMIT=${LIMIT:-"10"}

YEAR=`date "+%Y"`
MONTH=`date "+%m"`
DAY=`date "+%d"`
TODAY="${YEAR}-${MONTH}-${DAY}"

if [ ! -d themes/$THEME ] ; then
  echo "Theme not found, aborting."
  exit1
fi

if [ ! -f $DB ] ; then
  echo "DB not found, aborting."
  exit 1
fi

#
# main index - last X entries
#
OUT="build${BASE_URL}/index.html"
echo "building $OUT, last $LIMIT"
sed "s/{{TITLE}}/v2 - Last ${LIMIT} Entries/" themes/${THEME}/HEADER.html | \
  sed "s#{{BASE_URL}}#${BASE_URL}#g" > $OUT
echo "<h1>v2 - Last ${LIMIT} Entries</h1>" >> $OUT
grep -e "$DS" $DB | sed -e "s#^content/#/#" | \
  sort -r | head -${LIMIT} | \
  awk -f themes/${THEME}/index.awk -v baseurl="$BASE_URL" >> $OUT
sed "s/{{LAST_MOD}}/${TODAY}/" themes/${THEME}/FOOTER.html | \
  sed "s#{{BASE_URL}}#${BASE_URL}#g" >> $OUT


# all index
OUT="build${BASE_URL}/all.html"
echo "building $OUT"
sed "s/{{TITLE}}/v2 - All Entries/" themes/${THEME}/HEADER.html | \
  sed "s#{{BASE_URL}}#${BASE_URL}#g" > $OUT
echo "<h1>v2 - All Entries</h1>" >> $OUT
grep -e "$DS" $DB | sed -e "s#^content/#/#" | sort -r | \
  awk -f themes/${THEME}/index.awk -v baseurl="$BASE_URL" >> $OUT
sed "s/{{LAST_MOD}}/${TODAY}/" themes/${THEME}/FOOTER.html | \
  sed "s#{{BASE_URL}}#${BASE_URL}#g" >> $OUT

# EOF
